[package]
name = "rango-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file = "../../LICENSE"
publish = false
repository.workspace = true

[[bin]]
name = "rango"
path = "src/main.rs"

[dependencies]
rango-sdk = { path = "../sdk-rust" }
rango-storage = { path = "../storage" }
rango-oplog = { path = "../oplog" }
rango-sync = { path = "../sync" }
rango-types = { path = "../types" }
bson = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
aes-gcm = { workspace = true }
pbkdf2 = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
