from typing import Mapping, TypeVar

# Base document type — schemaless but structured
# More precise than Any; values must be objects (not untyped)
Document = Mapping[str, object]

# Generic type variable for future typed collections
T = TypeVar("T", bound=Document)

class RangoClient:
    """High-level Rango client with Pythonic API."""

    def __init__(self, core: object) -> None: ...
    def collection(self, name: str) -> Collection: ...
    @classmethod
    def connect(cls, path: str, node_id: str = "python-node") -> RangoClient: ...

class Collection:
    """Collection interface for CRUD operations."""

    def insert_one(self, doc: Document) -> str: ...
    def find_one(self, id: str) -> Document | None: ...
    def find_many(self) -> list[Document]: ...
    def update_one(self, id: str, update: Document) -> bool: ...
    def delete_one(self, id: str) -> bool: ...

def connect(path: str, node_id: str = "python-node") -> RangoClient: ...
